name: ci

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
          # fetch all commits so that the right version can be inferred
          fetch-depth: '0'

      # fetch all tags so that the right version can be inferred
      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Configure CI git user
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Authenticate with NPM registry
        run: |
          echo "@rareyes:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          npm whoami

      # - name: Publish package
      #   run: npm lerna publish --yes
